### ISSUE TITLE
Hotreload doesn't work 

### ISSUE THREAD

**Issue by vymarkov** [inosik/fable-vscode-rollup-sample#4]
I'd like to say a huge thank for this awesome sample :) I'm willing to use this sample for my next VS Code extension, but 
I've faced with an issue that don't allow to me to use hotreload. 

There is a short video that demonstrates the issue.
https://monosnap.com/file/RKDN2vA6JRA6KIua0lTd9BbOL31Sk6

May be there is a known issue (according to readme.md)

**Comment by inosik** [comment]
Hi @vymarkov! Thanks for bringing this to my attention, I wasn't aware that even the initial build is failing. I updated the sample to use the latest tools etc. The whole setup is a little bit simpler now as well.

I'm trying to figure out how to make a "hot" build work with <kbd>F5</kbd>, so stay tuned for that.

I hope this sample will be useful for you.

**Comment by inosik** [comment]
Hi @vymarkov, I've updated the sample with instructions, a new task and a new debug configuration to allow for basic rebuilding. I wouldn't consider this "hot reloading" though. I've found a [blog post](https://blog.hediet.de/post/hot_reload_for_vs_code_extension_development) which describes how it could be done, but I think this is outside of the scope of this sample.

**Comment by vymarkov** [comment]
@inosik thanks for new updates, I'd to add that I meant "hot reload" for F# code without the integration with VS Code.
It works awesome, many thanks!

**Comment by inosik** [comment]
You're welcome! I'll go ahead and close this issue.
