### ISSUE TITLE
How to register a command?

### ISSUE THREAD

**Issue by vymarkov** [inosik/fable-vscode-rollup-sample#5]
I want to register my own command, but it doesn't work due to wrong signature. I'm new to F#, so I don't any idea how it should like, so please share your idea :) Thanks in advance.

![image](https://user-images.githubusercontent.com/1110697/107534935-fa2fcd00-6bc8-11eb-8e2a-f918507e841d.png)

**Comment by inosik** [comment]
I've copied the bindings from the Ionide project, and it looks like these overloads are the ones that they needed. This particular API is a little bit tricky. I added some new overloads for this API in 09eba3caf78ed10a9b46aec2ee3aaccf6cd98a0a which should improve things a bit.

If you happen to need some references about Fable bindings, take a look at [the post by Zaid Ajaj](https://medium.com/@zaid.naom/f-interop-with-javascript-in-fable-the-complete-guide-ccc5b896a59f), or [the post by Francois Nicalse](https://medium.com/@whitetigle/even-more-interop-with-fable-7afb0e8db5b4). The Fable REPL is also really helpful when trying around with small code snippets.

And I hope your journey with F# and Fable isn't too bumpy so far 😅

**Comment by vymarkov** [comment]
> And I hope your journey with F# and Fable isn't too bumpy so far 😅

It's road of pain, most of examples, templates are outdated, lack of docs...

**Comment by vymarkov** [comment]
Thanks for updates, I'm going to close this issue

**Comment by inosik** [comment]
> It's road of pain, most of examples, templates are outdated, lack of docs...

Sorry to hear that. I hope you keep going though, and please don't hesitate to open issues or ask questions in the other channels (the Fable repo, the Fable Gitter channel etc.)
